// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserSex int32

const (
	User_MAN   UserSex = 0
	User_WOMEN UserSex = 1
)

var UserSex_name = map[int32]string{
	0: "MAN",
	1: "WOMEN",
}
var UserSex_value = map[string]int32{
	"MAN":   0,
	"WOMEN": 1,
}

func (x UserSex) String() string {
	return proto.EnumName(UserSex_name, int32(x))
}
func (UserSex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_ef6d5c294d5a1411, []int{2, 0}
}

type ListUsersRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int64    `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize             int64    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_ef6d5c294d5a1411, []int{0}
}
func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(dst, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *ListUsersRequest) GetPageNumber() int64 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *ListUsersRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListUsersResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *User    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_ef6d5c294d5a1411, []int{1}
}
func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (dst *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(dst, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListUsersResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListUsersResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Birthday             int32    `protobuf:"varint,5,opt,name=birthday,proto3" json:"birthday,omitempty"`
	IsVip                bool     `protobuf:"varint,6,opt,name=is_vip,json=isVip,proto3" json:"is_vip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_ef6d5c294d5a1411, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetBirthday() int32 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *User) GetIsVip() bool {
	if m != nil {
		return m.IsVip
	}
	return false
}

func init() {
	proto.RegisterType((*ListUsersRequest)(nil), "ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "ListUsersResponse")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterEnum("UserSex", UserSex_name, UserSex_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_ef6d5c294d5a1411) }

var fileDescriptor_user_ef6d5c294d5a1411 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcb, 0x4e, 0xc2, 0x40,
	0x14, 0x86, 0x19, 0xdb, 0x02, 0x3d, 0x6c, 0xe0, 0x44, 0x93, 0x01, 0x17, 0x36, 0x5d, 0x75, 0xd5,
	0x05, 0xfa, 0x02, 0xc6, 0xb8, 0x13, 0x4c, 0x86, 0xa8, 0x1b, 0x13, 0x32, 0xc0, 0x11, 0x26, 0xb1,
	0x17, 0x66, 0x5a, 0x22, 0x3c, 0x95, 0x8f, 0x68, 0x66, 0xaa, 0x8d, 0xd1, 0xdd, 0x7c, 0x5f, 0x9b,
	0xff, 0xdc, 0x00, 0x6a, 0x43, 0x3a, 0x2d, 0x75, 0x51, 0x15, 0xf1, 0x1b, 0x0c, 0x1f, 0x94, 0xa9,
	0x9e, 0x0c, 0x69, 0x23, 0x68, 0x5f, 0x93, 0xa9, 0xf0, 0x1c, 0x82, 0x7d, 0x4d, 0xfa, 0xc8, 0x59,
	0xc4, 0x92, 0x50, 0x34, 0x80, 0x57, 0x30, 0x28, 0xe5, 0x96, 0x96, 0x79, 0x9d, 0xad, 0x48, 0xf3,
	0xb3, 0x88, 0x25, 0x9e, 0x00, 0xab, 0xe6, 0xce, 0xe0, 0x25, 0x84, 0xee, 0x07, 0xa3, 0x4e, 0xc4,
	0x3d, 0xf7, 0xb9, 0x6f, 0xc5, 0x42, 0x9d, 0x28, 0x7e, 0x85, 0xd1, 0xaf, 0x3a, 0xa6, 0x2c, 0x72,
	0x43, 0x88, 0xe0, 0xaf, 0x8b, 0x0d, 0xb9, 0x3a, 0x9e, 0x70, 0x6f, 0xe4, 0xd0, 0xcb, 0xc8, 0x18,
	0xb9, 0x25, 0x57, 0x22, 0x14, 0x3f, 0x88, 0x63, 0xf0, 0x37, 0xb2, 0x92, 0x2e, 0x7a, 0x30, 0x0d,
	0x52, 0x9b, 0x25, 0x9c, 0x8a, 0x3f, 0x19, 0xf8, 0x16, 0x6d, 0x62, 0x2e, 0x33, 0xfa, 0xee, 0xdc,
	0xbd, 0x71, 0x02, 0x7d, 0x3b, 0xb0, 0xf3, 0x4d, 0x64, 0xcb, 0x76, 0x54, 0xca, 0xa4, 0x7a, 0x77,
	0xa1, 0xa1, 0x68, 0xc0, 0xda, 0x72, 0x57, 0xe4, 0xc4, 0xfd, 0xc6, 0x3a, 0xb0, 0x39, 0x2b, 0xa5,
	0xab, 0xdd, 0x46, 0x1e, 0x79, 0x10, 0xb1, 0x24, 0x10, 0x2d, 0xe3, 0x05, 0x74, 0x95, 0x59, 0x1e,
	0x54, 0xc9, 0xbb, 0x11, 0x4b, 0xfa, 0x22, 0x50, 0xe6, 0x59, 0x95, 0xf1, 0x18, 0x3c, 0x43, 0x1f,
	0xd8, 0x03, 0x6f, 0x76, 0x3b, 0x1f, 0x76, 0x30, 0x84, 0xe0, 0xe5, 0x71, 0x76, 0x3f, 0x1f, 0xb2,
	0xe9, 0x1d, 0x0c, 0x6c, 0xc7, 0x0b, 0xd2, 0x07, 0xb5, 0x26, 0xbc, 0x81, 0xb0, 0xdd, 0x0f, 0x8e,
	0xd2, 0xbf, 0x37, 0x99, 0x60, 0xfa, 0x6f, 0x7d, 0x71, 0x67, 0xd5, 0x75, 0x47, 0xbc, 0xfe, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0xfa, 0x4c, 0xd5, 0x3c, 0xd2, 0x01, 0x00, 0x00,
}
